// Real HTTP -> Express -> JWT middleware -> controllers. Supabase/Stripe transports mocked, RLS bypassed.
const fs=require('node:fs'),assert=require('node:assert/strict');
(async()=>{const {safeEnv,fixture,ids}=await import('./helpers/audit-fixture.js');safeEnv();const {auditTransport}=await import('./helpers/audit-transport.js');const state=fixture();const transport=auditTransport(state);const nativeFetch=global.fetch;global.fetch=transport.fetch;const {default:app}=await import('../src/app.js');const {stripe}=await import('../src/modules/subscriptions/stripeService.js');let stripeCalls=0;stripe.taxRates.retrieve=async()=>({id:'txr_fixture',active:true,livemode:false,percentage:21,inclusive:true,tax_type:'vat',country:'ES'});stripe.prices.retrieve=async()=>{stripeCalls++;return {active:true,livemode:false,tax_behavior:'inclusive',currency:'eur',unit_amount:1749,recurring:{interval:'month',interval_count:1}}};stripe.subscriptions.retrieve=async()=>{stripeCalls++;throw Error('not allowed in foreign request')};stripe.checkout.sessions.create=async()=>{stripeCalls++;return {id:'cs_fixture',url:'https://checkout.stripe.com/fixture'}};stripe.billingPortal.sessions.create=async()=>{stripeCalls++;return {url:'https://billing.stripe.com/fixture'}};
const server=await new Promise(resolve=>{const s=app.listen(0,'127.0.0.1',()=>resolve(s))});const base='http://127.0.0.1:'+server.address().port;const results=[];
async function request(name,token,method,path,body,expected){const r=await nativeFetch(base+path,{method,headers:{...(token?{Authorization:'Bearer '+token}:{}),'Content-Type':'application/json'},...(body!==undefined?{body:typeof body==='string'?body:JSON.stringify(body)}:{})});const text=await r.text();let data;try{data=JSON.parse(text)}catch{data={parseError:true}}const expectedCodes=Array.isArray(expected)?expected:[expected];const pass=expectedCodes.includes(r.status);results.push({name,identity:token??'anonymous',method,path,body,expected:expectedCodes,actual:r.status,pass});assert(pass,`${name}: expected ${expectedCodes}, received ${r.status}`);if(r.status>=400)assert(!text.includes('Private A')&&!text.includes('Private B'),'private data leak');return data}
try{
for(const token of [null,'','manipulated.jwt','expired-fixture','nonexistent-user'])await request('Invalid/absent authentication',token,'GET','/api/businesses',undefined,401);
for(const [token,business,menu,category,product]of [['qa-a',ids.b1,ids.mb1,ids.cb1,ids.pb1],['qa-b',ids.a1,ids.ma1,ids.ca1,ids.pa1],['qa-b',ids.a2,ids.ma2,ids.ca2,ids.pa2]]){
const before=JSON.stringify(state);for(const [method,path,body,expected]of [
['GET',`/api/businesses/${business}`,undefined,404],['PATCH',`/api/businesses/${business}`,{name:'Hacked',public_profile:{about:'Hacked'}},403],['DELETE',`/api/businesses/${business}`,undefined,404],
['GET',`/api/businesses/${business}/menus`,undefined,403],['POST',`/api/businesses/${business}/menus`,{name:'Hacked',slug:'hacked'},403],['GET',`/api/menus/${menu}`,undefined,403],['PATCH',`/api/menus/${menu}`,{is_published:true},403],['DELETE',`/api/menus/${menu}`,undefined,403],['POST',`/api/menus/${menu}/duplicate`,{},403],
['POST',`/api/menus/${menu}/categories`,{name:'Hacked'},403],['PATCH',`/api/categories/${category}`,{name:'Hacked'},403],['DELETE',`/api/categories/${category}`,undefined,403],['POST',`/api/categories/${category}/products`,{productId:product},403],['DELETE',`/api/categories/${category}/products/${product}`,undefined,403],
['GET',`/api/businesses/${business}/products`,undefined,403],['POST',`/api/businesses/${business}/products`,{name:'Hacked',price:1},403],['PATCH',`/api/products/${product}`,{price:0},403],['DELETE',`/api/products/${product}`,undefined,403],['POST',`/api/products/${product}/image`,{},403],['DELETE',`/api/products/${product}/image`,undefined,403],['PUT',`/api/products/${product}/allergens`,{allergenIds:[1]},403],
['PATCH',`/api/businesses/${business}/logo`,{path:business+'/11111111-1111-4111-8111-111111111111.png'},403],['DELETE',`/api/businesses/${business}/logo`,undefined,403],['POST',`/api/businesses/${business}/cover`,{},403],['DELETE',`/api/businesses/${business}/cover`,undefined,403],
['GET',`/api/menus/${menu}/theme`,undefined,403],['PUT',`/api/menus/${menu}/theme`,{},403],['POST',`/api/menus/${menu}/theme/publish`,{},403],['GET',`/api/menus/${menu}/languages`,undefined,403],['POST',`/api/menus/${menu}/languages/en/translate`,{},403],['PUT',`/api/menus/${menu}/languages/en/text`,{},403],
['GET',`/api/subscriptions/${business}`,undefined,403],['POST','/api/subscriptions/checkout',{businessId:business},403],['POST','/api/subscriptions/portal',{businessId:business},403],['POST','/api/subscriptions/checkout/cancel',{businessId:business},403]
])await request('Horizontal tenant attack',token,method,path,body,expected);
assert.equal(JSON.stringify(state),before,'Foreign attack mutated database');}
assert.equal(stripeCalls,0);
await request('A1 read own business','qa-a','GET',`/api/businesses/${ids.a1}`,undefined,200);await request('A2 separate subscription','qa-a','GET',`/api/subscriptions/${ids.a2}`,undefined,200);
await request('Cross-tenant nested product rejected','qa-a','POST',`/api/categories/${ids.ca1}/products`,{productId:ids.pb1},404);
await request('A1 cannot link A2 product despite same owner','qa-a','POST',`/api/categories/${ids.ca1}/products`,{productId:'eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeee'},400);
await request('Body does not override route tenant','qa-a','PATCH',`/api/products/${ids.pa1}?businessId=${ids.b1}`,{price:0,business_id:ids.b1},400);
await request('Direct billing state manipulation','qa-a','PATCH',`/api/subscriptions/${ids.a1}`,{status:'active'},404);
await request('Price/trial manipulation','qa-a','POST','/api/subscriptions/checkout',{businessId:ids.a1,price:'price_free',trialDays:365},400);
for(const path of ['/api/products/not-a-uuid','/api/categories/not-a-uuid','/api/menus/not-a-uuid'])await request('Malformed resource ID','qa-a','PATCH',path,{name:'Name'},400);
await request('Malformed JSON','qa-a','POST','/api/businesses','{invalid',400);
for(const slug of ['login','a'])await request('Reserved or malformed public slug','qa-a','POST','/api/businesses',{name:'Test',slug:'valid-slug',public_slug:slug},400);
const normalized=await request('Public slug safely normalized','qa-a','POST','/api/businesses',{name:'Test',slug:'valid-slug',public_slug:'Bad / Slug'},201);assert.equal(normalized.business.public_slug,'bad-slug');
await request('Mass assignment','qa-a','POST','/api/businesses',{name:'Test',slug:'valid-slug',owner_id:ids.b},400);
await request('Negative price','qa-a','POST',`/api/businesses/${ids.a1}/products`,{name:'Dish',price:-1},400);
state.subscriptions[0].status='past_due';await request('Subscription gate cannot be bypassed','qa-a','PATCH',`/api/products/${ids.pa1}`,{price:5},402);assert.equal(state.subscriptions[1].status,'active');
await request('Unpublished menu remains private',null,'GET',`/api/public/menus/${ids.a1}/principal`,undefined,404);
console.log('PASS',results.length,'real HTTP assertions with mocked auth/PostgREST/Stripe');
}finally{fs.writeFileSync(process.env.AUDIT_MATRIX_PATH || 'docs/preproduction/verification/security-matrix.json',JSON.stringify({type:'REAL_HTTP_MOCKED_SUPABASE_STRIPE_NO_RLS',results,stripeCalls,transportRequests:transport.history.length},null,2));await new Promise(r=>server.close(r));global.fetch=nativeFetch}})().catch(e=>{console.error(e);process.exitCode=1});
