// PostgreSQL integration against a disposable local database ONLY. Core schema is a documented approximation.
const {execFileSync,execFile}=require('node:child_process'),fs=require('node:fs'),path=require('node:path');
const database='carteliax_audit_'+Date.now();
const root=path.resolve(__dirname,'../..');const args=['-X','-h','/tmp/carteliax-audit/socket','-p','55438','-U','jordi','-d',database,'-v','ON_ERROR_STOP=1'];
const guard="DO $$BEGIN IF current_setting('port')<>'55438' OR current_setting('data_directory') <> '/tmp/carteliax-audit/pg' THEN RAISE EXCEPTION 'Disposable audit database required';END IF;END$$;";
function sql(text){return execFileSync('psql',[...args,'-c',guard+text],{encoding:'utf8'})}
function file(text){const filename='/tmp/carteliax-audit/statement.sql';fs.writeFileSync(filename,guard+'\n'+text);return execFileSync('psql',[...args,'-f',filename],{encoding:'utf8'})}
(async()=>{execFileSync('createdb',['-h','/tmp/carteliax-audit/socket','-p','55438','-U','jordi',database]);let schema=fs.readFileSync(root+'/docs/microsites/verification/schema-fixture.sql','utf8').replaceAll('55432','55438').replaceAll('/tmp/carteliax-languages/%','/tmp/carteliax-audit/%');console.log(file(schema));
console.log(sql("ALTER TABLE subscriptions ADD COLUMN stripe_customer_id text, ADD COLUMN stripe_subscription_id text, ADD COLUMN trial_used_at timestamptz, ADD COLUMN cancel_at_period_end boolean default false, ADD COLUMN checkout_attempt_id uuid, ADD COLUMN checkout_expires_at timestamptz, ADD COLUMN checkout_session_id text;CREATE TABLE stripe_webhook_events(id text primary key,event_type text);INSERT INTO businesses(id,owner_id,name,slug) values('99999999-9999-4999-8999-999999999999','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','A2','audit-a2');INSERT INTO subscriptions(business_id,status) values('99999999-9999-4999-8999-999999999999','inactive');"));
for(const name of ['202610060001_menu_translations.sql','202610070001_business_microsites.sql','202610080001_billing_webhook_safety.sql']){console.log('APPLY LOCAL',name);console.log(file(fs.readFileSync(root+'/supabase/migrations/'+name,'utf8')))}
for(const name of ['translations-database','translations-database-edges','translations-production-guards','translations-reuse','microsites-database']){let src=fs.readFileSync(root+'/backend/test/'+name+'.sql','utf8').replaceAll('55432','55438').replaceAll('/tmp/carteliax-languages/%','/tmp/carteliax-audit/%');console.log('TEST LOCAL',name);console.log(file(src))}
console.log(file(fs.readFileSync(root+'/backend/test/billing-database.sql','utf8')));const concurrent=(statement)=>new Promise((resolve,reject)=>execFile('psql',[...args,'-At','-c',guard+statement],{encoding:'utf8'},(error,out)=>error?reject(error):resolve(out.trim().split('\n').at(-1))));
console.log(sql("update subscriptions set status='inactive',checkout_attempt_id=null where business_id='99999999-9999-4999-8999-999999999999';"));
const winners=await Promise.all(['cccccccc-cccc-4ccc-8ccc-cccccccccccc','dddddddd-dddd-4ddd-8ddd-dddddddddddd'].map(attempt=>concurrent("with acquired as(update subscriptions set status='checkout_pending',checkout_attempt_id='"+attempt+"' where business_id='99999999-9999-4999-8999-999999999999' and status='inactive' and checkout_attempt_id is null returning business_id) select count(*) from acquired;")));
if(winners.sort().join(',')!=='0,1')throw Error('Concurrent Checkout CAS failed');console.log('PASS concurrent Checkout CAS: one PostgreSQL winner');
console.log(sql("update subscriptions set status='active',stripe_subscription_id='sub_parallel',stripe_customer_id='cus_parallel',stripe_event_created=0 where business_id='11111111-1111-4111-8111-111111111111';"));
const payload=JSON.stringify({business_id:'11111111-1111-4111-8111-111111111111',owner_id:'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',stripe_subscription_id:'sub_parallel',stripe_customer_id:'cus_parallel',status:'active',current_period_end:'2027-01-01T00:00:00Z',cancel_at_period_end:false});
const duplicate="select cx_sync_billing_event('evt_parallel','customer.subscription.updated',200,'"+payload+"');";
const outcomes=await Promise.all([concurrent(duplicate),concurrent(duplicate)]);
if(outcomes.sort().join(',')!=='duplicate,synced')throw Error('Concurrent webhook deduplication failed');console.log('PASS concurrent webhook delivery: one transaction, one duplicate');
console.log('PASS PostgreSQL local migrations + SQL security/regressions; production schema NOT certified');})().catch(e=>{console.error(e.stderr?.toString()??e.message);process.exitCode=1});
