\set ON_ERROR_STOP on
begin;
do $$begin if current_setting('port')<>'55432' or current_setting('data_directory') not like '/tmp/carteliax-languages/%' then raise exception 'Disposable fixture required';end if;end$$;
create function pg_temp.assert(ok boolean,label text) returns void language plpgsql as $$begin if ok is distinct from true then raise exception 'FAIL: %',label;end if;raise notice 'PASS: %',label;end$$;
create function pg_temp.reject(query text) returns void language plpgsql as $$begin begin execute query;exception when check_violation or unique_violation or insufficient_privilege then raise notice 'PASS: invalid write rejected';return;end;raise exception 'FAIL: invalid write succeeded';end$$;
select pg_temp.assert((select public_slug='restaurante-jordi' and slug='restaurante-jordi' from businesses where id='11111111-1111-4111-8111-111111111111'),'Legacy restaurant backfilled without changing historical address');
select pg_temp.assert((select count(*)=2 from menus),'Existing menus retained');
select pg_temp.assert((select count(*)=1 from products),'Existing products retained');
select pg_temp.assert(cx_public_profile_valid('{}'),'Empty optional profile accepted');
select pg_temp.assert(cx_public_profile_valid('{"hours":[{"day":0,"intervals":[{"open":"13:00","close":"16:00"},{"open":"20:00","close":"02:00"}]}]}'),'Two services and overnight valid');
select pg_temp.assert(not cx_public_profile_valid('{"hours":[{"day":0,"intervals":[]},{"day":0,"intervals":[]}]}'),'Duplicate days rejected');
select pg_temp.assert(not cx_public_profile_valid('{"hours":[{"day":0,"intervals":[{"open":"13:00","close":"16:00"},{"open":"15:00","close":"23:00"}]}]}'),'Overlapping services rejected');
select pg_temp.assert(not cx_public_profile_valid('{"hours":[{"day":0,"intervals":[{"open":"01:00","close":"03:00"},{"open":"20:00","close":"02:00"}]}]}'),'Overnight wrap overlap rejected');
select pg_temp.assert(not cx_public_profile_valid('{"hours":[{"day":0,"intervals":[{"open":"25:00","close":"02:00"}]}]}'),'Invalid clock rejected');
select pg_temp.assert(not cx_public_profile_valid('{"unknown":true}'),'Unknown fields rejected');
select pg_temp.assert(not cx_public_profile_valid('{"about":"<script>alert(1)</script>"}'),'HTML rejected');
select pg_temp.assert(not cx_public_profile_valid('{"instagram":"javascript:alert(1)"}'),'Unsafe scheme rejected');
select pg_temp.assert(not cx_public_profile_valid('{"instagram":"https://instagram.com.evil.test/me"}'),'Host spoofing rejected');
select pg_temp.assert(not cx_public_profile_valid('{"maps_url":"https://evil.test/me"}'),'Arbitrary map host rejected');
select pg_temp.assert(not cx_public_profile_valid('{"website":"https://user:pass@example.com/me"}'),'URL credentials rejected');
select pg_temp.assert(cx_public_profile_valid('{"instagram":"https://www.instagram.com/me","maps_url":"https://maps.app.goo.gl/abc"}'),'Valid social and map links accepted');
select pg_temp.assert(cx_public_profile_valid('{"translations":[{"language":"en","description":"Our kitchen","about":"About us","source":"text"}]}'),'Persisted manual texts accepted');
select pg_temp.assert(not cx_public_profile_valid('{"translations":[{"language":"en","description":"<iframe>","about":"About us","source":"text"}]}'),'Translated HTML rejected');
select pg_temp.reject($q$update businesses set public_slug='new-address' where id='11111111-1111-4111-8111-111111111111'$q$);
select pg_temp.reject($q$insert into businesses(owner_id,name,slug,public_slug) values('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','Conflict','conflict','restaurante-jordi')$q$);
select pg_temp.reject($q$insert into businesses(owner_id,name,slug,public_slug) values('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','Login','login','login')$q$);
select pg_temp.reject($q$insert into businesses(owner_id,name,slug,public_slug) values('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','Nuxt','nuxt','nuxt')$q$);
insert into businesses(owner_id,name,slug) values('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','Conflict','restaurante-jordi'),('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','Login','login');
select pg_temp.assert((select count(distinct public_slug)=count(*) from businesses),'Auto allocation unique including collisions');
select pg_temp.assert((select bool_and(cx_public_slug_valid(public_slug)) from businesses),'Auto allocation always avoids reserved routes');
update businesses set name='Nuevo nombre' where id='11111111-1111-4111-8111-111111111111';
select pg_temp.assert((select public_slug='restaurante-jordi' from businesses where id='11111111-1111-4111-8111-111111111111'),'Rename preserves printed QR address');
set local role authenticated;
set local request.jwt.claim.sub='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb';
update businesses set public_profile='{"about":"Foreign edit"}' where id='11111111-1111-4111-8111-111111111111';
select pg_temp.reject($q$insert into storage.objects(bucket_id,name) values('business-covers','11111111-1111-4111-8111-111111111111/99999999-9999-4999-8999-999999999999.webp')$q$);
set local request.jwt.claim.sub='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa';
insert into storage.objects(bucket_id,name) values('business-covers','11111111-1111-4111-8111-111111111111/99999999-9999-4999-8999-999999999999.webp');
select pg_temp.assert((select count(*)=1 from storage.objects),'Owner cover permitted');
select pg_temp.reject($q$insert into storage.objects(bucket_id,name) values('business-covers','11111111-1111-4111-8111-111111111111/../attack.webp')$q$);
reset role;
select pg_temp.assert((select public_profile='{}' from businesses where id='11111111-1111-4111-8111-111111111111'),'Foreign write did not alter profile');
set local role anon;
select pg_temp.reject($q$select * from businesses$q$);
reset role;
rollback;
