import test from 'node:test';import assert from 'node:assert/strict';import {ids,fixture,memoryDb,response,safeEnv} from './helpers/audit-fixture.js';
safeEnv();
const {supabaseAdmin}=await import('../src/infrastructure/database/supabase.js');
const {stripe}=await import('../src/modules/subscriptions/stripeService.js');
const {createCheckout,createPortal,cancelPendingCheckout}=await import('../src/modules/subscriptions/subscriptionController.js');
const {stripeWebhook}=await import('../src/modules/subscriptions/stripeWebhookController.js');
const {requireActiveSubscription}=await import('../src/middlewares/requireActiveSubscription.js');
const {createProductSchema}=await import('../src/modules/products/productSchemas.js');
const price={active:true,livemode:false,tax_behavior:'inclusive',unit_amount:1749,currency:'eur',recurring:{interval:'month',interval_count:1}};
const subscription=(id='sub_0',status='active')=>({id,customer:'cus_0',status,livemode:false,metadata:{business_id:ids.a1,owner_id:ids.a},items:{data:[{price:{id:'price_fixture'},quantity:1,current_period_end:Math.floor(Date.now()/1000)+86400}]}});
function signed(event){const body=Buffer.from(JSON.stringify(event));return {body,headers:{'stripe-signature':stripe.webhooks.generateTestHeaderString({payload:body.toString(),secret:'whsec_fixture'})}}}
test('preproduction regressions: isolated database and Stripe transports',async t=>{
t.mock.method(stripe.taxRates,'retrieve',async()=>({id:'txr_fixture',active:true,livemode:false,percentage:21,inclusive:true,tax_type:'vat',country:'ES'}));
t.mock.method(stripe.customers,'retrieve',async()=>({livemode:false,tax_exempt:'none',balance:0}));
t.mock.method(stripe.invoiceItems,'list',async()=>({data:[]}));
await t.test('simultaneous Checkout creates exactly one session',async t=>{const s=fixture();s.subscriptions=[];const db=memoryDb(s);t.mock.method(supabaseAdmin,'from',db.from);t.mock.method(stripe.prices,'retrieve',async()=>price);let calls=0;t.mock.method(stripe.checkout.sessions,'create',async()=>({id:'cs_'+(++calls),url:'https://checkout.stripe.com/fixture'}));const req={body:{businessId:ids.a1},user:{id:ids.a}};const a=response(),b=response();await Promise.all([createCheckout(req,a),createCheckout(req,b)]);assert.equal(calls,1);assert.deepEqual([a.statusCode,b.statusCode].sort(),[200,409])});
await t.test('Checkout fixes seven-day trial and payment method; used trial cannot repeat',async t=>{for(const used of [false,true]){const s=fixture();if(!used)s.subscriptions=[];else Object.assign(s.subscriptions[0],{status:'canceled'});t.mock.method(supabaseAdmin,'from',memoryDb(s).from);t.mock.method(stripe.prices,'retrieve',async()=>price);t.mock.method(stripe.subscriptions,'retrieve',async()=>subscription('sub_0','canceled'));let payload,options;t.mock.method(stripe.checkout.sessions,'create',async(p,o)=>{payload=p;options=o;return {id:'cs_trial',url:'https://checkout.stripe.com/fixture'}});const res=response();await createCheckout({body:{businessId:ids.a1},user:{id:ids.a,email:'a@example.invalid'}},res);assert.equal(res.statusCode,200);assert.equal(payload.payment_method_collection,'always');assert.deepEqual(payload.automatic_tax,{enabled:false});assert.equal(payload.allow_promotion_codes,false);assert.deepEqual(payload.subscription_data.default_tax_rates,['txr_fixture']);assert.deepEqual(payload.line_items,[{price:'price_fixture',quantity:1}]);assert.equal(payload.subscription_data.trial_period_days,used?undefined:7);assert.equal(payload.subscription_data.metadata.business_id,ids.a1);assert.equal(payload.subscription_data.metadata.owner_id,ids.a);assert.equal(payload.subscription_data.metadata.checkout_attempt_id,s.subscriptions.find(x=>x.business_id===ids.a1).checkout_attempt_id);assert.match(options.idempotencyKey,/^checkout_/);}});
await t.test('wrong commercial price never creates Checkout',async t=>{const s=fixture();s.subscriptions=[];t.mock.method(supabaseAdmin,'from',memoryDb(s).from);t.mock.method(stripe.prices,'retrieve',async()=>({...price,unit_amount:1800}));let calls=0;t.mock.method(stripe.checkout.sessions,'create',async()=>{calls++;return {id:'cs_bad',url:'https://checkout.stripe.com/bad'}});const res=response();await createCheckout({body:{businessId:ids.a1},user:{id:ids.a}},res);assert.equal(calls,0);assert.equal(res.statusCode,503)});
await t.test('Stripe network ambiguity retains reservation',async t=>{const s=fixture();s.subscriptions=[];t.mock.method(supabaseAdmin,'from',memoryDb(s).from);t.mock.method(stripe.prices,'retrieve',async()=>price);t.mock.method(stripe.checkout.sessions,'create',async()=>{throw Object.assign(new Error('simulated lost reply'),{type:'StripeConnectionError'})});const res=response();await createCheckout({body:{businessId:ids.a1},user:{id:ids.a}},res);assert.equal(res.statusCode,503);assert.equal(s.subscriptions[0].status,'checkout_pending');assert(s.subscriptions[0].checkout_attempt_id)});
await t.test('completed old session without webhook cannot be paid twice',async t=>{const s=fixture();Object.assign(s.subscriptions[0],{status:'checkout_pending',stripe_subscription_id:null,checkout_session_id:'cs_old',checkout_attempt_id:'old',checkout_expires_at:'2020-01-01T00:00:00Z'});t.mock.method(supabaseAdmin,'from',memoryDb(s).from);t.mock.method(stripe.prices,'retrieve',async()=>price);t.mock.method(stripe.checkout.sessions,'retrieve',async()=>({id:'cs_old',status:'complete'}));let calls=0;t.mock.method(stripe.checkout.sessions,'create',async()=>{calls++;return {id:'cs_new',url:'https://checkout.stripe.com/new'}});const res=response();await createCheckout({body:{businessId:ids.a1},user:{id:ids.a}},res);assert.equal(calls,0);assert.equal(res.statusCode,409)});
await t.test('legacy pending Checkout with no session or attempt cannot be cleared by expiry',async t=>{const s=fixture();Object.assign(s.subscriptions[0],{status:'checkout_pending',stripe_subscription_id:null,checkout_session_id:null,checkout_attempt_id:null,checkout_expires_at:'2020-01-01T00:00:00Z'});t.mock.method(supabaseAdmin,'from',memoryDb(s).from);const res=response();await cancelPendingCheckout({body:{businessId:ids.a1},user:{id:ids.a}},res);assert.equal(res.statusCode,409);assert.equal(s.subscriptions[0].status,'checkout_pending');});
await t.test('foreign Checkout, cancel and portal are rejected before Stripe',async t=>{const s=fixture();t.mock.method(supabaseAdmin,'from',memoryDb(s).from);for(const fn of [createCheckout,cancelPendingCheckout,createPortal]){const res=response();await fn({body:{businessId:ids.b1},user:{id:ids.a}},res);assert.equal(res.statusCode,403)}});
await t.test('shared legacy Stripe customer blocks Checkout and Portal',async t=>{const s=fixture();s.subscriptions[1].stripe_customer_id=s.subscriptions[0].stripe_customer_id;t.mock.method(supabaseAdmin,'from',memoryDb(s).from);let calls=0;t.mock.method(stripe.subscriptions,'retrieve',async()=>{calls++;return subscription()});t.mock.method(stripe.billingPortal.sessions,'create',async()=>{calls++;return {url:'https://billing.stripe.com/fixture'}});for(const fn of [createCheckout,createPortal]){const res=response();await fn({body:{businessId:ids.a1},user:{id:ids.a}},res);assert.equal(res.statusCode,409);}assert.equal(calls,0)});
await t.test('forged webhook signatures are rejected with no DB writes',async()=>{for(const headers of [{},{'stripe-signature':'forged'}]){const res=response();await stripeWebhook({headers,body:Buffer.from('{}')},res);assert.equal(res.statusCode,400)}});
await t.test('live webhook on test backend is rejected before any DB access',async t=>{let calls=0;t.mock.method(supabaseAdmin,'from',()=>{calls++;throw Error('must not touch DB')});const res=response();await stripeWebhook(signed({id:'evt_live',type:'customer.subscription.updated',livemode:true,data:{object:subscription()}}),res);assert.equal(res.statusCode,400);assert.equal(calls,0)});
for(const status of ['trialing','active','past_due','unpaid','canceled','incomplete','incomplete_expired','paused','checkout_pending','inactive'])await t.test('billing access '+status,async t=>{const s=fixture();Object.assign(s.subscriptions[0],{status,trial_ends_at:new Date(Date.now()+86400000).toISOString()});t.mock.method(supabaseAdmin,'from',memoryDb(s).from);const res=response();let allowed=false;await requireActiveSubscription('business')({params:{id:ids.a1},user:{id:ids.a}},res,()=>{allowed=true});assert.equal(allowed,['active','trialing'].includes(status));if(!allowed)assert.equal(res.statusCode,402)});
await t.test('expired trial/period and database outage fail closed',async t=>{for(const status of ['active','trialing']){const s=fixture();Object.assign(s.subscriptions[0],{status,current_period_end:'2020-01-01',trial_ends_at:'2020-01-01'});t.mock.method(supabaseAdmin,'from',memoryDb(s).from);const res=response();await requireActiveSubscription('business')({params:{id:ids.a1},user:{id:ids.a}},res,()=>assert.fail('unexpected access'));assert.equal(res.statusCode,402)}t.mock.method(supabaseAdmin,'from',()=>{throw Error('DB offline')});const res=response();await requireActiveSubscription('business')({params:{id:ids.a1},user:{id:ids.a}},res,()=>assert.fail('unexpected access'));assert.equal(res.statusCode,500)});
await t.test('negative, nonfinite, excessive decimals and mass assignment rejected',()=>{for(const price of [-1,NaN,Infinity,1.001,1000000])assert.equal(createProductSchema.safeParse({name:'Dish',price}).success,false);assert.equal(createProductSchema.safeParse({name:'Dish',price:1,owner_id:ids.b,business_id:ids.b1}).success,false);assert(createProductSchema.safeParse({name:'Café 🍽️',price:999999.99}).success)});
});
