-- LOCAL ONLY: original schema approximation; never execute on Supabase.
\set ON_ERROR_STOP on
do $$begin if current_setting('port')<>'55432' or current_setting('data_directory') not like '/tmp/carteliax-languages/%' then raise exception 'Disposable fixture required';end if;end$$;
do $$begin if not exists(select 1 from pg_roles where rolname='anon') then create role anon nologin;end if;end$$;
do $$begin if not exists(select 1 from pg_roles where rolname='authenticated') then create role authenticated nologin;end if;end$$;
do $$begin if not exists(select 1 from pg_roles where rolname='service_role') then create role service_role nologin bypassrls;end if;end$$;
create extension if not exists pgcrypto;
create schema auth;
create schema storage;
create table auth.users(id uuid primary key);
create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
grant usage on schema public,auth,storage to anon,authenticated,service_role;
grant execute on function auth.uid() to anon,authenticated,service_role;
create table profiles(id uuid primary key references auth.users(id));
create table businesses(id uuid primary key default gen_random_uuid(),owner_id uuid references auth.users(id),name text,slug text,description text,default_language text default 'es',logo_url text,primary_color text default '#047857',is_active boolean default true,created_at timestamptz default now());
create table menus(id uuid primary key default gen_random_uuid(),business_id uuid references businesses(id),name text,slug text,description text,is_published boolean default false,sort_order int default 0,created_at timestamptz default now());
create table categories(id uuid primary key default gen_random_uuid(),menu_id uuid references menus(id),name text,description text,is_visible boolean default true,sort_order int default 0);
create table products(id uuid primary key default gen_random_uuid(),business_id uuid references businesses(id),name text,description text,price numeric,image_url text,is_available boolean default true);
create table category_products(category_id uuid references categories(id),product_id uuid references products(id),sort_order int default 0);
create table menu_themes(id uuid primary key default gen_random_uuid(),menu_id uuid unique references menus(id),draft_config jsonb default '{}',published_config jsonb default '{}',published_at timestamptz,updated_at timestamptz default now());
create table subscriptions(business_id uuid references businesses(id),status text,trial_ends_at timestamptz,current_period_end timestamptz);
create table allergens(id int primary key,code text,name_es text);
create table product_allergens(product_id uuid references products(id),allergen_id int references allergens(id));
create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
create table storage.objects(id uuid default gen_random_uuid(),bucket_id text references storage.buckets(id),name text);
create function storage.foldername(text) returns text[] language sql immutable as $$select string_to_array($1,'/')$$;
alter table storage.objects enable row level security;
alter table businesses enable row level security;
create policy fixture_owner on businesses to authenticated using(owner_id=auth.uid()) with check(owner_id=auth.uid());
grant select,insert,update,delete on businesses,storage.objects to authenticated;
grant all on all tables in schema public,storage to service_role;
create function duplicate_menu(p_menu_id uuid) returns uuid language plpgsql security definer as $$declare orig menus;new_id uuid:=gen_random_uuid();begin select * into orig from menus where id=p_menu_id;insert into menus(id,business_id,name,slug,description) values(new_id,orig.business_id,orig.name||' copia',orig.slug||'-copia',orig.description);return new_id;end$$;
insert into auth.users values('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa'),('bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb');
insert into profiles select id from auth.users;
insert into businesses(id,owner_id,name,slug,description) values('11111111-1111-4111-8111-111111111111','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','Restaurante Jordi','restaurante-jordi','Cocina de temporada'),('22222222-2222-4222-8222-222222222222','bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb','Otro','otro','Otra cocina');
insert into menus(id,business_id,name,slug,is_published) values('33333333-3333-4333-8333-333333333333','11111111-1111-4111-8111-111111111111','Carta principal','principal',true),('44444444-4444-4444-8444-444444444444','22222222-2222-4222-8222-222222222222','Otra','otra',false);
insert into categories values('55555555-5555-4555-8555-555555555555','33333333-3333-4333-8333-333333333333','Arroces',null,true,0);
insert into products values('77777777-7777-4777-8777-777777777777','11111111-1111-4111-8111-111111111111','Paella para 2 personas','Arroz casero',18,null,true);
insert into category_products values('55555555-5555-4555-8555-555555555555','77777777-7777-4777-8777-777777777777',0);
insert into menu_themes(menu_id,draft_config,published_config,published_at) values('33333333-3333-4333-8333-333333333333','{"branding":{"welcomeText":"Hola"}}','{"branding":{"welcomeText":"Hola"}}',now());
insert into subscriptions values('11111111-1111-4111-8111-111111111111','active',null,null),('22222222-2222-4222-8222-222222222222','active',null,null);
