<script setup lang="ts">
import type { PublicProfile } from '~/types/publicSite';
const profile = defineModel<PublicProfile>({ required: true });
const props = defineProps<{ description: string; sourceLanguage: string }>();
const templates = [{id:'modern',name:'Moderna',description:'Fresca y cercana'},{id:'elegant',name:'Elegante',description:'Sobria y distinguida'},{id:'minimal',name:'Minimal',description:'Solo lo esencial'},{id:'classic',name:'Clásica',description:'Cálida y tradicional'}];
const days = ['Lunes','Martes','Miércoles','Jueves','Viernes','Sábado','Domingo'];
const languages = [{ code:'es',name:'Español' },{ code:'val',name:'Valencià / Català' },{ code:'en',name:'English' },{ code:'fr',name:'Français' }];
const language = ref('en');
const targetLanguages = computed(() => languages.filter(l => l.code !== (props.sourceLanguage === 'ca' ? 'val' : props.sourceLanguage)));
watch(targetLanguages, options => { if (!options.some(l => l.code === language.value)) language.value = options[0]?.code ?? ''; }, { immediate: true });
const invalidFields = reactive<Record<string, string>>({});
function invalidField(event: Event) { const input = event.target as HTMLInputElement; if (input.id) invalidFields[input.id] = input.validity.customError ? input.validationMessage : input.title || 'Revisa este campo antes de guardar.'; }
function clearInvalid(event: Event) { const input = event.target as HTMLInputElement; delete invalidFields[input.id]; if (['site-about','site-address','site-city','site-postal_code','site-trans-description','site-trans-about'].includes(input.id)) input.setCustomValidity(/[<>]/.test(input.value) ? 'Utiliza texto normal, sin etiquetas HTML.' : ''); }
const translation = computed(() => profile.value.translations.find(t=>t.language===language.value));
const source = computed(() => JSON.stringify([props.description.trim(),profile.value.about.trim(),props.sourceLanguage]));
const fields = [
 {key:'phone',label:'Teléfono',type:'tel',max:30},{key:'whatsapp',label:'WhatsApp (con prefijo de país)',type:'tel',max:16},{key:'email',label:'Email público',type:'email',max:254},
 {key:'address',label:'Dirección',type:'text',max:240},{key:'city',label:'Localidad',type:'text',max:100},{key:'postal_code',label:'Código postal',type:'text',max:20},{key:'maps_url',label:'Enlace de Google Maps',type:'url',max:2048},
 {key:'instagram',label:'Instagram',type:'url',max:2048},{key:'facebook',label:'Facebook',type:'url',max:2048},{key:'tiktok',label:'TikTok',type:'url',max:2048},{key:'website',label:'Otra web (opcional)',type:'url',max:2048},
] as const;
function fieldPattern(key: string) {
 if (key === 'phone') return '\\+?[0-9 \\(\\)\\-]{6,30}';
 if (key === 'whatsapp') return '\\+?[0-9]{7,15}';
 const domains: Record<string, string> = {instagram:'(?:www\\.)?instagram\\.com',facebook:'(?:www\\.)?facebook\\.com',tiktok:'(?:www\\.)?tiktok\\.com',maps_url:'(?:www\\.google\\.com|google\\.com|maps\\.google\\.com|maps\\.app\\.goo\\.gl|goo\\.gl)'};
 return domains[key] ? `https://${domains[key]}(?:/.*|\\?.*|#.*)?` : key === 'website' ? 'https://.*' : undefined;
}
function fieldHelp(key: string) {
 return key === 'whatsapp' ? 'Prefijo de país y número, sin espacios. Ejemplo: +34600000000.' : key === 'maps_url' ? 'Pega el enlace compartido desde Google Maps.' : ['instagram','facebook','tiktok','website'].includes(key) ? 'Pega el enlace completo, empezando por https://.' : '';
}
function scheduleState(day:number) { const row=profile.value.hours.find(d=>d.day===day);return !row?'unknown':row.intervals.length?'open':'closed'; }
function setSchedule(day:number,event:Event) { const value=(event.target as HTMLSelectElement).value;profile.value.hours=profile.value.hours.filter(d=>d.day!==day);if(value!=='unknown')profile.value.hours.push({day,intervals:value==='closed'?[]:[{open:'13:00',close:'16:00'}]}); }
function setTranslation(field:'description'|'about',event:Event) { let row=translation.value;if(!row){row={language:language.value,description:'',about:'',source:source.value};profile.value.translations.push(row);}row[field]=(event.target as HTMLTextAreaElement).value;row.source=source.value; }
</script>
<template>
 <div class="profile-editor" @invalid.capture="invalidField" @input="clearInvalid">
  <div><h2 class="text-xl font-bold">Tu mini web</h2><p class="ui-description">Los campos vacíos se ocultan. Al guardar, estos datos aparecen en tu web pública.</p></div>
  <fieldset><legend>Elige el estilo de tu web</legend><div class="template-options"><label v-for="option in templates" :key="option.id" :class="[{selected:profile.template===option.id},`template-${option.id}`]"><input v-model="profile.template" type="radio" :value="option.id" name="site-template"/><span class="template-thumb" aria-hidden="true"><i/><b/><em/><span/></span><span class="template-name">{{ option.name }}<small>{{ option.description }}</small></span></label></div><p class="help">Una plantilla para toda tu web: portada, cartas, productos y contacto. Las opciones de contenido de cada carta se conservan.</p></fieldset>
  <div><label for="site-about">Sobre nosotros</label><textarea id="site-about" v-model="profile.about" rows="4" maxlength="3000" placeholder="Cuenta vuestra historia, cocina o especialidad…"/></div>
  <details open><summary>Contacto y ubicación</summary><div class="field-grid"><div v-for="field in fields.slice(0,7)" :key="field.key"><label :for="`site-${field.key}`">{{ field.label }}</label><input :id="`site-${field.key}`" v-model="profile[field.key]" :type="field.type" :aria-invalid="invalidFields[`site-${field.key}`] ? true : undefined" :pattern="fieldPattern(field.key)" :title="fieldHelp(field.key) || undefined" :aria-describedby="fieldHelp(field.key) ? `help-${field.key}` : undefined" :maxlength="field.max" :placeholder="field.type==='url'?'https://…':field.key==='whatsapp'?'+34600000000':''"/><p v-if="fieldHelp(field.key)" :id="`help-${field.key}`" class="help">{{ fieldHelp(field.key) }}</p><p v-if="invalidFields[`site-${field.key}`]" class="text-sm text-red-700" role="alert">{{ invalidFields[`site-${field.key}`] }}</p></div></div><p class="help">Comparte el enlace de Google Maps. El mapa se muestra a partir de la dirección, sin contratar una API.</p></details>
  <details><summary>Redes sociales y web</summary><div class="field-grid"><div v-for="field in fields.slice(7)" :key="field.key"><label :for="`site-${field.key}`">{{ field.label }}</label><input :id="`site-${field.key}`" v-model="profile[field.key]" :type="field.type" :aria-invalid="invalidFields[`site-${field.key}`] ? true : undefined" :pattern="fieldPattern(field.key)" :title="fieldHelp(field.key) || undefined" :aria-describedby="fieldHelp(field.key) ? `help-${field.key}` : undefined" :maxlength="field.max" placeholder="https://…"/><p :id="`help-${field.key}`" class="help">{{ fieldHelp(field.key) }}</p><p v-if="invalidFields[`site-${field.key}`]" class="text-sm text-red-700" role="alert">{{ invalidFields[`site-${field.key}`] }}</p></div></div></details>
  <details><summary>Horario del restaurante</summary><p class="help">Puedes indicar dos turnos. Si cierras antes de la hora de apertura, se entiende que cierras al día siguiente.</p><div v-for="(day,index) in days" :key="day" class="schedule-day"><label :for="`day-${index}`">{{ day }}</label><select :id="`day-${index}`" :value="scheduleState(index)" @change="setSchedule(index,$event)"><option value="unknown">Sin indicar</option><option value="closed">Cerrado</option><option value="open">Abierto</option></select><template v-for="row in profile.hours.filter(d=>d.day===index)" :key="row.day"><div v-for="(interval,i) in row.intervals" :key="i" class="time-row"><input v-model="interval.open" type="time" required :aria-label="`${day}, apertura ${i+1}`"/><span>–</span><input v-model="interval.close" type="time" required :aria-label="`${day}, cierre ${i+1}`"/><button type="button" class="ui-quiet" :aria-label="`Quitar turno ${i+1} del ${day}`" @click="row.intervals.splice(i,1)">Quitar</button></div><button v-if="row.intervals.length===1" type="button" class="ui-quiet" @click="row.intervals.push({open:'20:00',close:'23:00'})">Añadir segundo turno</button></template></div></details>
  <details><summary>Textos de la web en otros idiomas</summary><p class="help">Completa manualmente la descripción y Sobre nosotros. Los platos se traducen desde Idiomas de cada carta. Un texto vacío conserva el original.</p><label for="site-translation-language">Idioma del texto</label><select id="site-translation-language" v-model="language"><option v-for="l in targetLanguages" :key="l.code" :value="l.code">{{ l.name }}</option></select><p v-if="translation && translation.source!==source" role="status" class="help text-amber-800">El original cambió. Revisa estos textos; hasta entonces la web muestra el original.</p><label for="site-trans-description">Descripción traducida</label><textarea id="site-trans-description" :value="translation?.description ?? ''" maxlength="500" rows="3" @input="setTranslation('description',$event)"/><label for="site-trans-about">Sobre nosotros traducido</label><textarea id="site-trans-about" :value="translation?.about ?? ''" maxlength="3000" rows="4" @input="setTranslation('about',$event)"/><div v-if="translation" class="flex flex-wrap gap-3"><button v-if="translation.source!==source" type="button" class="ui-secondary" @click="translation.source=source">He revisado la traducción</button><button type="button" class="ui-quiet" @click="profile.translations=profile.translations.filter(t=>t.language!==language)">Quitar estos textos traducidos</button></div></details>
 </div>
</template>
<style scoped>
.profile-editor{display:grid;gap:24px;padding-top:0}.profile-editor label,legend{display:block;font-size:14px;font-weight:600;margin-bottom:8px}.profile-editor input:not([type=radio]),.profile-editor textarea,.profile-editor select{width:100%;min-width:0;min-height:44px;padding:10px 12px;border:1px solid #cbd5e1;border-radius:8px;background:#fff}.profile-editor textarea{margin-bottom:12px}.field-grid{display:grid;gap:16px;margin-top:20px}.help{font-size:13px;color:#64748b;line-height:1.7;margin:12px 0}.template-options{display:grid;grid-template-columns:repeat(2,1fr);gap:8px}.template-options label{position:relative;display:flex;flex-direction:column;align-items:stretch;gap:10px;padding:9px;border:1px solid #cbd5e1;border-radius:8px;margin:0}.template-options .selected{border-color:#059669;background:#ecfdf5}details{border-top:1px solid #e2e8f0;padding-top:16px}summary{font-weight:600;cursor:pointer;min-height:44px}.schedule-day{display:grid;grid-template-columns:1fr 1fr;gap:10px;padding:14px 0;border-bottom:1px solid #f1f5f9;align-items:center}.time-row{grid-column:1/-1;display:flex;gap:8px;align-items:center}.time-row input{flex:1;width:80px!important}.time-row button{font-size:12px;padding:8px}.schedule-day>button{grid-column:1/-1}@media(min-width:640px){.field-grid{grid-template-columns:1fr 1fr}.template-options{grid-template-columns:repeat(4,1fr)}}
.template-options input{position:absolute;top:17px;right:17px;width:16px;height:16px;accent-color:var(--ui-accent);z-index:1}.template-thumb{display:flex;flex-direction:column;gap:5px;padding:16px 12px;height:94px;border-radius:5px;background:#e9f1e9;align-items:flex-start}.template-thumb i{display:block;width:16px;height:16px;border-radius:50%;background:#387458;margin-bottom:3px}.template-thumb b{height:5px;width:55%;background:#285344;border-radius:4px}.template-thumb em{height:3px;width:70%;background:#a5c0ac;border-radius:4px}.template-thumb>span{height:17px;width:100%;background:#fff;border-radius:4px;margin-top:4px}.template-name{display:block;font-size:13px;padding:3px 3px 5px}.template-name small{display:block;font-size:10px;font-weight:400;color:var(--ui-muted);margin-top:4px}.template-elegant .template-thumb{background:#232d29}.template-elegant .template-thumb b{background:#e7dbba}.template-elegant .template-thumb i{background:#bba773}.template-elegant .template-thumb>span{background:#424b3e}.template-minimal .template-thumb{background:#f6f6f2;border:1px solid #e3e5df;border-radius:0}.template-minimal .template-thumb i{border-radius:0;background:#47594c}.template-classic .template-thumb{background:#f4e8d2;align-items:center}.template-classic .template-thumb i{background:#9c7545}.template-classic .template-thumb b{background:#705331}.template-classic .template-thumb>span{border-top:3px double #c2a376}.template-options label:focus-within{outline:3px solid var(--ui-accent);outline-offset:3px}.profile-editor details{border:1px solid var(--ui-border);border-radius:var(--ui-radius);padding:14px 16px}.profile-editor details[open]{background:#fafbf8}.profile-editor summary{min-height:30px;line-height:30px}.profile-editor details:not([open]) summary{min-height:30px}.profile-editor .field-grid input{background:#fff}.profile-editor .help{color:var(--ui-secondary-text)}
</style>
